name: Set Closed Date Field

on:
  issues:
    types: [closed]

jobs:
  set-date:
    runs-on: ubuntu-latest
    steps:
      - name: Update project field
        uses: actions/github-script@v7
        with:
          script: |
            const projectId = "3"; 
            const fieldId = "267407437"; 

            const closedAt = new Date().toISOString().split("T")[0];

            await github.graphql(`
              mutation(
                $projectId: ID!
                $issueId: ID!
                $fieldId: ID!
                $closedAt: String!
              ) {
                updateProjectV2ItemFieldValue(
                  input: {
                    projectId: $projectId
                    itemId: $issueId
                    fieldId: $fieldId
                    value: { text: $closedAt }
                  }
                ) {
                  projectV2Item { id }
                }
              }
            `, {
              projectId,
              issueId: context.payload.issue.node_id,
              fieldId,
              closedAt
            });
